import { Montserrat } from "next/font/google";
import "./globals.css";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata = {
  title: "Kobo Kanaeru x Tokopedia",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/icon-kobo.png" type="image/png" sizes="any" />
      </head>
      <body className={montserrat.className}>{children}</body>
    </html>
  );
}
